# Generated by Django 5.1.7 on 2025-06-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_interesttag_user_interests_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态')),
                ('reviewed_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to='accounts.user', verbose_name='审核人')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='accounts.school', verbose_name='所属学校')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.user', verbose_name='发布用户')),
            ],
            options={
                'verbose_name': '论坛帖子',
                'verbose_name_plural': '论坛帖子',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('interest_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.interesttag', verbose_name='兴趣标签')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='forum.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子标签',
                'verbose_name_plural': '帖子标签',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'interest_tag')},
            },
        ),
    ]
