# Generated by Django 5.1.7 on 2025-06-27 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_interesttag_user_interests_selected_and_more'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='违规词/模式')),
                ('pattern', models.TextField(blank=True, verbose_name='正则表达式')),
                ('category', models.CharField(choices=[('political', '政治敏感'), ('adult', '色情内容'), ('violence', '暴力血腥'), ('advertisement', '垃圾广告'), ('abuse', '恶意谩骂'), ('other', '其他违规')], max_length=20, verbose_name='违规类别')),
                ('severity', models.IntegerField(default=2, help_text='1-警告，2-拒绝，3-严重违规', verbose_name='严重程度')),
                ('match_type', models.CharField(choices=[('exact', '精确匹配'), ('contains', '包含匹配'), ('regex', '正则表达式'), ('fuzzy', '模糊匹配')], default='contains', max_length=10, verbose_name='匹配方式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '违规词库',
                'verbose_name_plural': '违规词库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='auto_approved',
            field=models.BooleanField(default=False, verbose_name='自动审核通过'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_result',
            field=models.CharField(blank=True, max_length=50, verbose_name='审核结果详情'),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('title', '标题'), ('content', '正文'), ('both', '标题和正文')], max_length=20, verbose_name='内容类型')),
                ('original_content', models.TextField(verbose_name='原始内容')),
                ('detected_words', models.TextField(default='[]', help_text='JSON格式存储', verbose_name='检测到的违规词')),
                ('action', models.CharField(choices=[('approved', '通过'), ('blocked', '拒绝'), ('warning', '警告')], max_length=20, verbose_name='处理动作')),
                ('violation_category', models.CharField(blank=True, max_length=20, verbose_name='违规类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.post', verbose_name='关联帖子')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '内容审核日志',
                'verbose_name_plural': '内容审核日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
