# Generated by Django 5.1.7 on 2025-06-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_interesttag_user_interests_selected_and_more'),
        ('forum', '0002_violationword_post_auto_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='forum.post', verbose_name='帖子')),
                ('interest_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.interesttag', verbose_name='兴趣标签')),
            ],
            options={
                'verbose_name': '帖子标签',
                'verbose_name_plural': '帖子标签',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='posttag',
            unique_together={('post', 'interest_tag')},
        ),
    ]
