# Generated by Django 5.1.7 on 2025-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_editor",
            field=models.BooleanField(default=False, verbose_name="是否博主"),
        ),
    ] 