# Generated by Django 5.1.7 on 2025-06-25 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('planned_duration', models.IntegerField(verbose_name='计划时长(分钟)')),
                ('actual_duration', models.IntegerField(blank=True, null=True, verbose_name='实际时长(分钟)')),
                ('task_title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('task_description', models.TextField(blank=True, verbose_name='任务描述')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('session_type', models.CharField(choices=[('work', '工作'), ('break', '休息')], default='work', max_length=10, verbose_name='会话类型')),
                ('interrupted', models.BooleanField(default=False, verbose_name='是否被中断')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '专注会话',
                'verbose_name_plural': '专注会话',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FocusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_duration', models.IntegerField(default=25, verbose_name='工作时长(分钟)')),
                ('break_duration', models.IntegerField(default=5, verbose_name='休息时长(分钟)')),
                ('long_break_duration', models.IntegerField(default=15, verbose_name='长休息时长(分钟)')),
                ('sessions_before_long_break', models.IntegerField(default=4, verbose_name='长休息前的会话数')),
                ('sound_enabled', models.BooleanField(default=True, verbose_name='启用声音提醒')),
                ('auto_start_breaks', models.BooleanField(default=False, verbose_name='自动开始休息')),
                ('auto_start_work', models.BooleanField(default=False, verbose_name='自动开始工作')),
                ('focus_theme', models.CharField(default='default', max_length=20, verbose_name='专注主题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='focus_settings', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '专注设置',
                'verbose_name_plural': '专注设置',
            },
        ),
    ]
