# Generated by Django 5.1.7 on 2025-06-27 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_focussession_focussettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='标签颜色')),
                ('category', models.CharField(max_length=50, verbose_name='标签分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '兴趣标签',
                'verbose_name_plural': '兴趣标签',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='interests_selected',
            field=models.BooleanField(default=False, verbose_name='是否已选择兴趣标签'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests_selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='选择兴趣标签时间'),
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='选择时间')),
                ('interest_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.interesttag', verbose_name='兴趣标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户兴趣',
                'verbose_name_plural': '用户兴趣',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'interest_tag')},
            },
        ),
    ]
