# Generated by Django 5.1.7 on 2025-07-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_interesttag_user_interests_selected_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="focussettings",
            name="user",
        ),
        migrations.DeleteModel(
            name="FocusSession",
        ),
        migrations.DeleteModel(
            name="FocusSettings",
        ),
    ]
