# Generated by Django 5.1.7 on 2025-06-27 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_interesttag_user_interests_selected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务名称')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name='时间要求')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_checkins', to='accounts.user', verbose_name='创建者')),
            ],
            options={
                'verbose_name': '打卡任务',
                'verbose_name_plural': '打卡任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_id', models.IntegerField(verbose_name='打卡任务ID')),
                ('checkin_title', models.CharField(blank=True, max_length=200, verbose_name='打卡任务名称')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('checkin_date', models.DateField(default=django.utils.timezone.now, verbose_name='打卡日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checkins', to='accounts.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户打卡记录',
                'verbose_name_plural': '用户打卡记录',
                'ordering': ['-checked_at'],
                'unique_together': {('user', 'checkin_id', 'checkin_date')},
            },
        ),
    ]
