# Generated by Django 5.1.7 on 2025-07-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="target_distance",
            field=models.IntegerField(default=0, verbose_name="目标距离(米)"),
        ),
        migrations.AddField(
            model_name="checkin",
            name="target_duration",
            field=models.IntegerField(default=0, verbose_name="目标时长(分钟)"),
        ),
        migrations.AddField(
            model_name="checkin",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("study", "学习类"),
                    ("sport", "运动类"),
                    ("habit", "习惯养成"),
                    ("health", "健康类"),
                    ("other", "其他"),
                ],
                default="other",
                max_length=20,
                verbose_name="任务类型",
            ),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="notes",
            field=models.TextField(blank=True, verbose_name="打卡备注"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="sport_distance",
            field=models.IntegerField(default=0, verbose_name="运动距离(米)"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="sport_duration",
            field=models.IntegerField(default=0, verbose_name="运动时长(秒)"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="sport_end_location",
            field=models.JSONField(default=dict, verbose_name="结束位置"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="sport_start_location",
            field=models.JSONField(default=dict, verbose_name="起始位置"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="sport_trajectory",
            field=models.JSONField(default=list, verbose_name="运动轨迹"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="study_duration",
            field=models.IntegerField(default=0, verbose_name="学习时长(秒)"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="study_end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="学习结束时间"
            ),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="study_start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="学习开始时间"
            ),
        ),
    ]
