# Generated by Django 5.1.7 on 2025-07-03 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_interesttag_user_interests_selected_and_more"),
        ("checkin", "0002_checkin_target_distance_checkin_target_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportTrackingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_id", models.IntegerField(verbose_name="打卡任务ID")),
                (
                    "checkin_title",
                    models.CharField(max_length=200, verbose_name="打卡任务名称"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "is_paused",
                    models.BooleanField(default=False, verbose_name="是否暂停"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "pause_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="暂停时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "total_paused_duration",
                    models.IntegerField(default=0, verbose_name="总暂停时长(秒)"),
                ),
                (
                    "current_distance",
                    models.IntegerField(default=0, verbose_name="当前距离(米)"),
                ),
                (
                    "current_trajectory",
                    models.JSONField(default=list, verbose_name="当前轨迹"),
                ),
                (
                    "start_location",
                    models.JSONField(default=dict, verbose_name="起始位置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "运动追踪会话",
                "verbose_name_plural": "运动追踪会话",
                "ordering": ["-created_at"],
                "unique_together": {("user", "checkin_id", "is_active")},
            },
        ),
    ]
