# Generated by Django 5.1.7 on 2025-07-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_interesttag_user_interests_selected_and_more"),
        ("checkin", "0003_sporttrackingsession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="target_distance",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="sport_distance",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="sport_duration",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="sport_end_location",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="sport_start_location",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="sport_trajectory",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="study_duration",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="study_end_time",
        ),
        migrations.RemoveField(
            model_name="usercheckin",
            name="study_start_time",
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="duration",
            field=models.IntegerField(default=0, verbose_name="完成时长(秒)"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="usercheckin",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="task_type",
            field=models.CharField(
                choices=[("study", "学习类"), ("sport", "运动类"), ("other", "其他")],
                default="other",
                max_length=20,
                verbose_name="任务类型",
            ),
        ),
        migrations.CreateModel(
            name="CheckinSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_id", models.IntegerField(verbose_name="打卡任务ID")),
                (
                    "checkin_title",
                    models.CharField(max_length=200, verbose_name="打卡任务名称"),
                ),
                ("task_type", models.CharField(max_length=20, verbose_name="任务类型")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "is_paused",
                    models.BooleanField(default=False, verbose_name="是否暂停"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "pause_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="暂停时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "total_paused_duration",
                    models.IntegerField(default=0, verbose_name="总暂停时长(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "打卡会话",
                "verbose_name_plural": "打卡会话",
                "ordering": ["-created_at"],
                "unique_together": {("user", "checkin_id", "is_active")},
            },
        ),
        migrations.DeleteModel(
            name="SportTrackingSession",
        ),
    ]
