# Generated by Django 5.1.7 on 2025-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0004_remove_checkin_target_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercheckin",
            name="shared_to_community",
            field=models.BooleanField(default=False, verbose_name="是否已分享到社区"),
        ),
    ]
