# Generated by Django 5.1.7 on 2025-07-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0005_usercheckin_shared_to_community"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkin",
            name="task_type",
        ),
        migrations.RemoveField(
            model_name="checkinsession",
            name="task_type",
        ),
    ]
